export default  {
  LOG_IN: 'log_in',
  LOG_IN_ERROR: 'login_error',
  LOG_IN_SUCCESS: 'login_success',

  LOG_OUT: 'log_out',
  LOG_OUT_SUCCESS: 'logout_success',
  LOG_OUT_ERROR: 'logout_error',

  FETCH_USER_PROFILE: 'fetch_user_profile',
  FETCH_USER_SUCCESS: 'fetch_user_success',

  FETCH_USER_PICKS: 'fetch_user_picks',
  FETCH_USER_PICKS_SUCCESS: 'fetch_user_picks_success',
  FETCH_USER_PICKS_ERROR: 'fetch_user_picks_error',

  FETCH_NOTES: 'fetch_notes',
  ['instance1/FETCH_NOTES_SUCCESS']: 'fetch_notes_success_1',
  ['instance2/FETCH_NOTES_SUCCESS']: 'fetch_notes_success_2',
  FETCH_NOTES_ERROR: 'fetch_notes_error',

  SIGN_UP: 'sign_up',
  SIGN_UP_SUCCESS: 'sign_up_success',
  SIGN_UP_ERROR: 'sign_up_error',
  SET_NEW_USER: 'set_new_user',

  RESTAURANT_UPLOAD: 'restaurant_upload',
  RESTAURANT_UPLOAD_SUCCESS: 'restaurant_upload_success',
  RESTAURANT_UPLOAD_ERROR: 'restaurant_upload_error',
  ['instance1/RESTAURANT_REFRESH']: 'restaurant_refresh_1',
  ['instance2/RESTAURANT_REFRESH']: 'restaurant_refresh_2',

  UPLOAD_NEXT_PAGE: 'upload_next_page',
  UPLOAD_MOVE_BACK: 'upload_move_back',
  UPLOAD_ADD_NOTES: 'upload_add_notes',

  SEARCH_NEXT_PAGE: 'search_next_page',
  SEARCH_MOVE_BACK: 'search_move_back',
  LOCAL_PICKS_REFRESH:'local_picks_refresh',
  FETCH_LOCAL_PICKS: 'fetch_local_picks',
  FETCH_LOCAL_PICKS_SUCCESS: 'fetch_local_picks_success',
  FETCH_LOCAL_PICKS_ERROR: 'fetch_local_picks_error',

  FETCH_PROFILE: 'fetch_profile',
  ['instance1/FETCH_PROFILE_SUCCESS']: 'fetch_profile_success_1',
  ['instance2/FETCH_PROFILE_SUCCESS']: 'fetch_profile_success_2',
  ['instance1/PROFILE_GO_BACK']: 'profile_go_back_1',
  ['instance2/PROFILE_GO_BACK']: 'profile_go_back_2',
  ['instance1/CLEAR_PROFILES']: 'clear_profiles_1',
  ['instance2/CLEAR_PROFILES']: 'clear_profiles_2',

  FIND_NEW_AVATAR: 'find_new_avatar',
  FIND_NEW_AVATAR_SUCCESS: 'find_new_avatar_success',
  FIND_NEW_AVATAR_ERROR: 'find_new_avatar_error',
  EDIT_PROFILE: 'edit_profile',
  EDIT_PROFILE_SUCCESS: 'edit_profile_success',
  EDIT_PROFILE_ERROR: 'edit_profile_error',
  CANCEL_EDIT: 'cancel_edit',
  CANCEL_EDIT_SUCCESS: 'cancel_edit_success',
  CANCEL_EDIT_ERROR: 'cancel_edit_error',
  EDIT_FIRSTNAME:'edit_firstname',
  EDIT_LASTNAME: 'edit_lastname',
  EDIT_USERNAME: 'edit_username',

//ADD NOTES/DELETE LOCAL PICK OPTIONS
  OPEN_OVERLAY: 'open_overlay',
  CLOSE_OVERLAY: 'close_overlay',
  ADD_NEW_NOTES: 'add_new_notes',
  EDIT_NOTE: 'edit_note',
  USER_NOTE_PRESSED: 'user_note_pressed',
  USER_NOTE_CLOSED: 'user_note_closed',
  USER_NOTE_DELETED: 'user_note_deleted',
  USER_NOTE_DELETED_SUCCESS: 'user_note_deleted_success',
  USER_NOTE_DELETED_ERROR: 'user_note_deleted_error',
  DELETE_LOCAL_PICK: 'delete_local_pick',
  DELETE_LOCAL_PICK_SUCCESS: 'delete_local_pick_success',
}
